version = 1

test_patterns = [
  "test/**/*.*",
  "**/*.test.*"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "vitest",
    "browser"
  ]

[[transformers]]
name = "prettier"